FooBarRentals/config/routes.rb
Rails.application.routes.draw do

  resources :monkeys do
      resources :monkey_rental_requests
  end

end

FooBarRentals/app/models/monkey.rb
class Monkey < ActiveRecord::Base
include ActionView::Helpers::DateHelper
  validates :name, :birth_date, :color, :sex, :description, presence: true
  validates :sex, length:{ is: 1}

  has_many :monkey_rental_requests, dependent: :destroy

  def age
      start_date = self.birth_date
    finish_date = Date.today

    distance_of_time_in_words(start_date, finish_date)
  end
end

FooBarRentals/app/models/monkey_rental_request.rb
class MonkeyRentalRequest < ActiveRecord::Base
  validates :monkey_id, :start_date, :end_date, :status, presence: true

  belongs_to :monkey

  def same_monkey_requests
    self.monkey.monkey_rental_requests.where("id != ?", self.id)
  end

  def overlapping?(start, finish)
    (self.start_date < finish) && (start < self.end_date)
  end

  def overlapping_requests
    same_monkey_requests.select do |request|
      self.overlapping?(request.start_date, request.end_date)
    end
  end

  def overlapping_approved_requests
    overlapping_requests.select { |request| request.status == "APPROVED" }
  end

  # def overlapping_pending_requests
  # end

end

FooBarRentals/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

FooBarRentals/app/controllers/monkey_rental_requests_controller.rb
class MonkeyRentalRequestsController < ApplicationController

  def index
    @monkey = Monkey.find(params[:monkey_id])
    @requests = @monkey.monkey_rental_requests
    render 'monkeys/show'
  end

  def new
    render 'monkeys/show'
  end

  def create
    @monkey = Monkey.find(params[:monkey_id])
    @requests = @monkey.monkey_rental_requests
    fparams = request_params
    fparams[:monkey_id] = params[:monkey_id]
    @new_request = MonkeyRentalRequest.new(fparams)
    if @new_request.save
      render 'monkeys/show'
    else
      p @new_request.errors.full_messages
      render 'monkeys/show'
    end
  end

  def request_params
    params.require(:monkey_rental_request).permit(:start_date, :end_date)
  end
end

FooBarRentals/app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  def index
    @monkeys = Monkey.all
    render :index
  end

  def show
    @monkey = Monkey.find(params[:id])
    @requests = @monkey.monkey_rental_requests
    render :show
  end

  def new
    @monkey = Monkey.new
    render :new
  end

  def edit
    @monkey = Monkey.find(params[:id])
    render :edit
  end

  def create
    @new_monkey = Monkey.new(monkey_params)
    if @new_monkey.save
      redirect_to monkey_url(@new_monkey)
    else
      p @new_monkey.errors.full_messages
      render :new
    end
  end

  def update
    @monkey = Monkey.find(params[:id])
    if @monkey.update(monkey_params)
      redirect_to monkey_url(@monkey)
    else
      p @monkey.errors.full_messages

      render :edit
    end
  end

  private
  def monkey_params
    params.require(:monkey).permit(:birth_date, :color, :name, :sex, :description)
  end
end

FooBarRentals/app/helpers/application_helper.rb
module ApplicationHelper
end

FooBarRentals/app/helpers/monkey_rental_requests_helper.rb
module MonkeyRentalRequestsHelper
end

FooBarRentals/app/helpers/monkeys_helper.rb
module MonkeysHelper
end

FooBarRentals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FooBarRentals</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

FooBarRentals/app/views/monkeys/_form.html.erb
<% if @monkey.persisted? %>
  <% action = monkey_url(@monkey) %>
  <% method = "PATCH" %>
<% else %>
  <% action = monkeys_url %>
  <% method = "POST" %>
<% end %>
<form action="<%=action%>" method="POST">
  <input type="hidden" value = "<%=method%>" name="_method" />
  <label>Name:
    <input type="text" name="monkey[name]" value="<%=@monkey.name%>"/>
  </label>
  <br>
  <label>Date of Monkey Birth:
    <input type="date" name="monkey[birth_date]" value="<%=@monkey.birth_date%>"/>
  </label>
  <br>
  <label>Colour of Monkey:
    <input type="text" name="monkey[color]" value="<%=@monkey.color%>"/>
  </label>
  <br>
  <label>Binary Gender Distinction:
    <input type="radio" name="monkey[sex]" value="M"
      <% if @monkey.sex == 'M'%><%='checked="checked"'%><% end %> />
    <input type="radio" name="monkey[sex]" value="F"
      <% if @monkey.sex == 'F'%><%='checked="checked"'%><% end %>/>
  </label>
  <br>
  <label>Describe your monkey:
    <textarea name="monkey[description]"><%=@monkey.description%></textarea
  </label>
  <br>
  <input type="submit" value='SUBMIT MONKEY!'/>
</form>

FooBarRentals/app/views/monkeys/_rental_proposal.html.erb
<form action="<%=monkey_monkey_rental_requests_url(@monkey)%>" method="POST">
  <label>Date of proposed Monkey Acquisition:
    <input type="date" name="monkey_rental_request[start_date]"/>
  </label>
  <br>
  <label>Date of proposed Monkey Forfeiture:
    <input type="date" name="monkey_rental_request[end_date]"/>
  </label>
  <br>
  <input type="submit" value='SUBMIT PROPOSAL!'/>
</form>

FooBarRentals/app/views/monkeys/edit.html.erb
<%= render "form" %>
<!-- <form action="<%=monkey_path%>" method="POST">
  <input type="hidden" name="_method" value="PATCH" />
  <label>Name:
    <input type="text" name="monkey[name]" value="<%=@monkey.name%>"/>
  </label>
  <br>
  <label>Date of Monkey Birth:
    <input type="date" name="monkey[birth_date]" value="<%=@monkey.birth_date%>"/>
  </label>
  <br>
  <label>Colour of Monkey:
    <input type="text" name="monkey[color]" value="<%=@monkey.color%>"/>
  </label>
  <br>
  <label>Binary Gender Distinction:
    <input type="radio" name="monkey[sex]" value="M"
      <% if @monkey.sex == 'M'%><%='checked="checked"'%><% end %> />
    <input type="radio" name="monkey[sex]" value="F"
      <% if @monkey.sex == 'F'%><%='checked="checked"'%><% end %>/>
  </label>
  <br>
  <label>Describe your monkey:
    <textarea name="monkey[description]"><%=@monkey.description%></textarea
  </label>
  <br>
  <input type="submit" value='UPDATE MONKEY!'/>
</form> -->

FooBarRentals/app/views/monkeys/index.html.erb
<h1> All The Monkeys! </h1>

<ul>
  <% @monkeys.each do |monkey| %>
  <li>
    <a href="<%= monkey_url(monkey) %>"><%= monkey.name %></a>
  </li>
  <% end %>
</ul>

FooBarRentals/app/views/monkeys/new.html.erb
<%= render "form" %>
<!-- <form action="/monkeys" method="POST">
  <label>Name:
    <input type="text" name="monkey[name]" />
  </label>
  <br>
  <label>Date of Monkey Birth:
    <input type="date" name="monkey[birth_date]" />
  </label>
  <br>
  <label>Colour of Monkey:
    <input type="text" name="monkey[color]" />
  </label>
  <br>
  <label>Binary Gender Distinction:
    <input type="radio" name="monkey[sex]" value="M"/>
    <input type="radio" name="monkey[sex]" value="F"/>
  </label>
  <br>
  <label>Describe your monkey:
    <textarea name="monkey[description]" ></textarea
  </label>
  <br>
  <input type="submit" value='MAKE MONKEY!'/>
</form> -->

FooBarRentals/app/views/monkeys/show.html.erb
<h1><%= @monkey.name %></h1>

<table>
  <tr>
    <td>
      Day of Birth:
    </td>
    <td>
      Hue of Fur:
    </td>
    <td>
      Type of Genitals:
    </td>
    <td>
      Description of Monkey:
    </td>
  </tr>
  <tr>
    <td>
      <%= @monkey.birth_date %>
    </td>
    <td>
      <%= @monkey.color %>
    </td>
    <td>
      <%= @monkey.sex %>
    </td>
    <td>
      <%= @monkey.description %>
    </td>
  </tr>
</table>

<h1>This monkey presently has <%= @requests.count %> request(s) to be rented.</h1>
<% @requests.each do |request| %>
  <p>Dates during which monkey rental is proposed to occur (respectively)</p>
  <p><%= request.start_date %> to <%= request.end_date %></p>
<% end %>
<%= render "monkeys/rental_proposal" %>
<!-- <table>
  <tr>
    <td>
      Day of Birth:
    </td>
    <td>
      Hue of Fur:
    </td>
    <td>
      Type of Genitals:
    </td>
    <td>
      Description of Monkey:
    </td>
  </tr>
  <tr>
    <td>
      <%= @monkey.birth_date %>
    </td>
    <td>
      <%= @monkey.color %>
    </td>
    <td>
      <%= @monkey.sex %>
    </td>
    <td>
      <%= @monkey.description %>
    </td>
  </tr>
</table> -->